### ISSUE TITLE
appType is not read correctly from package.json

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-manifest#13]
When a `package.json` file is used as the source for the manifest, the `appType` property in the package file is ignored. The app type in the target manifest will always be "APP".

For example the following `package.json` should result in a manifest with `"appType": "DASHBOARD_WIDGET"`:

``` json
{
  "name": "social-media-dashboard-app",
  "version": "1.0.0-beta-0",
  "description": "An app for DHIS 2 that enables embedding media from external sites in dashboard items",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dhis2/social-media-dashboard-app.git"
  },
  "keywords": [
    "dhis",
    "hisp",
    "dashboard",
    "youtube",
    "video"
  ],
  "author": "Nicolay Ramm <nicolay@dhis2.org> (https://www.dhis2.org)",
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/dhis2/social-media-dashboard-app/issues"
  },
  "homepage": "https://github.com/dhis2/social-media-dashboard-app#readme",
  "devDependencies": {
    "d2-manifest": "^1.0.0-3"
  },
  "manifest.webapp": {
    "icons": {
      "48": "logo_youtube.png"
    },
    "appType": "DASHBOARD_WIDGET"
  }
}
```

**Comment by nicolayr** [comment]
A workaround for this problem is to specify the app type on the command line:

`d2-manifest package.json -t DASHBOARD_WIDGET manifest.webapp`

**Comment by adhbh** [comment]
@nicolayr 
One question: 
If neither package.json has appType, nor do we provide it using -t flag, should manifest file still have appType by default?

**Comment by Markionium** [comment]
@adhbh It doesn't have to but we should probably make `APP` the default type.

**Comment by nicolayr** [comment]
I think it should, because that way it's less magical to users what's going on. There's always the option to explicitly turn it off using `--no-type`

**Comment by Markionium** [comment]
With it doesn't I ment that DHIS 2 will assume it's of type APP, which is why we should probably default to that.

**Comment by nicolayr** [comment]
I was replying to @adhbh not arguing with you by the way, @Markionium - you just replied too quickly ;)

**Comment by adhbh** [comment]
This issue was because the manifest created from reading package.json file here :- https://github.com/dhis2/d2-manifest/blob/master/d2-manifest.js#L125

was getting overwritten by manifest created by default args.manifest value over here :- https://github.com/dhis2/d2-manifest/blob/master/d2-manifest.js#L171

This default value was present, even if we run `d2-manifest.js package.json manifest.webapp`  and hence the following was always true:- https://github.com/dhis2/d2-manifest/blob/master/d2-manifest.js#L146

Please check the solution here : https://github.com/dhis2/d2-manifest/compare/master...adhbh:typeapp?expand=1

As suggest, I have covered  the following cases in my solution:-
1. `d2-manifest.js package.json manifest.webapp`
   i. If package.json does not contain appType - default "appType":"APP" should be written in manifest.
   ii. If package.json contain appType, that value should be written in manifest.
2. `d2-manifest.js package.json --no-type manifest.webapp` :- manifest file should not contain appType irrespective package.json contains appType or not.
3. `d2-manifest.js package.json -t DASHBOARD manifest.webapp` :- "appType":"DASHBOARD_WIDGET" should be written in manifest irrespective of any value of appType in package.json.

Please let me know if I have missed anything or any change is required.

**Comment by adhbh** [comment]
@nicolayr 
I saw something late so I have added a commit and updated PR:
https://github.com/dhis2/d2-manifest/compare/master...adhbh:typeapp?expand=1

This is a better solution which also fixes this issue and made sure that these cases are satisfied.

**Comment by nicolayr** [comment]
@adhbh that seems to be the correct behaviour indeed. However since you mentioned the fact that the problem stems from the default value, it occurred to me that this was just a silly mistake on my part and the solution is very simple:

The default value should go in the [`defaultValues` object](https://github.com/dhis2/d2-manifest/blob/master/d2-manifest.js#L62), not as a default command line argument. That simple change should take care of all cases, except when `--no-type` is specified, which will need special handling.

**Comment by adhbh** [comment]
@nicolayr yeah i have already made that change. I saw the defaultValues object late. :)
Please check the above comment 👍

**Comment by nicolayr** [comment]
Seems to work perfectly. Thanks again @adhbh 👍
